http://localhost:3000/products

###
POST http://localhost:3000/products HTTP/1.1

{
    "name": "Exemplo 5",
    "price": 105.99,
    "productImage": 
}

###
GET http://localhost:3000/products/5b0d1d5c706ee51768fd2dce

###
DELETE http://localhost:3000/products/5b0d1d5c706ee51768fd2dce
###

PATCH http://localhost:3000/products/5b0d1d5c706ee51768fd2dce
content-type: application/json

[{
    "proName": "name", "value": "Exemplo Alterado"
}
]

###

POST http://localhost:3000/orders
content-type: application/json

{
    "productId": "5b0deec710e8b21661677528",
    "quantity": "2"
}
###

GET http://localhost:3000/orders
###

GET http://localhost:3000/orders/5b0ff8c87883361862ea02a2
###

DELETE  http://localhost:3000/orders/5b0ff8c87883361862ea02a2


#### USERS
POST http://localhost:3000/user/signup
content-type: application/json

{
    "email": "teste@.com",
    "password": "123456"
}